version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: fog
      MYSQL_ROOT_PASSWORD: password
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./fog.sql:/docker-entrypoint-initdb.d/fog.sql
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - "80:80"
      - "443:443"
    tty: true
    volumes:
       - fog-images:/images
       - fog-settings:/opt/fog/.fogsettings

  tftp:
    image: 



volumes:
    db-data:
    fog-settings:
    fog-images:
