version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: fog
      MYSQL_ROOT_PASSWORD: password
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./build/docker/fog_db/db.sql:/docker-entrypoint-initdb.d/db.sql
  web:
    build:
      context: ./build/docker/fog_web
      dockerfile: Dockerfile
    depends_on:
      - db
      - tftp
    links:
      - db
      - tftp
    ports:
      - "80:80"
      - "443:443"
    tty: true
    volumes:
       - fog-images:/images
       - fog-settings:/opt/fog/.fogsettings
       - tftpd_boot:/var/www/html/fog/tftp/


  tftp:
    build:
      dockerfile: Dockerfile
      context: ./build/docker/fog_tftpd/
    restart: unless-stopped
    environment:
      # An interface and a port to listen to. "0.0.0.0" means all interfaces
      TFTPD_BIND_ADDRESS: "0.0.0.0:1069"
      # Search the man page for --blocksize to learn more
      TFTPD_EXTRA_ARGS: '--blocksize 1468'
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - SYS_CHROOT
    ports:
      - 69:1069/udp
    volumes:
      - tftpd_boot:/tftpboot/boot
      - tftpd_configuration:/tftpboot/pxelinux.cfg:ro

volumes:
    db-data:
    fog-settings:
    fog-images:
    tftpd_boot:
    tftpd_configuration:
    fogproject_master:
